package com.example.domain.models

enum class ResourceName {
    WORKSPACE_SECTION_WORKSPACE,
    WORKSPACE_SECTION_PROJECTS,
    WORKSPACE_SECTION_TASKS,
    WORKSPACE_SECTION_USERS,
    WORKSPACE_SECTION_ACTIONS,
}